name: build-and-push-image

on:
  push:
    branches:
      - master
        
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: fwing
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fwing/tgmemobot:latest
            
      - name: Build and push photos
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile_photos
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fwing/tgmemobot:photos